### PR TITLE
Removing SPA configuration, clarifying content negotiation

### LINKED ISSUE #62: Regarding Produces & SPA Configuration
Hey all, I've been digging into the implementation of our recent decisions regarding the produces option and I'm having some issues.

I don’t believe our framework should be responsible for serving someone’s SPA entry path.  I believe that should be the responsibility of the developer. If someone is using Stormpath with a SPA, all they need (and want) is the JSON API that allows them to use login, registration, etc.  Why should an authentication library be handling my SPA for me?

As such, I don’t think we should be responding with 406 when a browser is requesting text/html, but only application/json has been place in the produces list.  In this situation I think we should pass on the request, and assume that something else (that the developer has configured) will render the HTML response (the SPA entry).

### PR DESCRIPTION
**Pull request by robertjd**
Output of yesterday’s meeting, please review!

Closes #62

### CODE REVIEW

**Comment by nbarbettini** [comment]
FYI: Impacts #57

**Comment by robertjd** [comment]
Yes, I removed the 405 behavior in this PR

**Comment by edjiang** [comment]
Looks good to me, I would suggest that you change on `requests.md` though:

From:

> If the request specifies `Accept: */*`, the first Content-Type in `stormpath:web:produces` will be returned.

To something like this:

If the request prefers `*/*` over `application/json` and `text/html`

Many browsers will do something like `Accept: text/html, */*`, and it wasn't clear that if there was a header like `Accept: text/xml, */*` what would happen.

**Comment by nbarbettini** [comment]
I agree, it should be clear in `requests.md` that we need to do true sorting of Accept, taking `q` values into account.

**Comment by robertjd** [comment]
@nbarbettini and @edjiang see edits in eb6b99f58545553fde520dba7afc0e5b59c6da2b, is this what you were noting?

**Comment by edjiang** [comment]
Looks great!

**Comment by nbarbettini** [comment]
LGTM :+1:

**Pull request merged**
