### PR TITLE
Add details to Change Password section

### LINKED ISSUE #86: Change Password section missing some details
I think [this section](https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md#post-handling) is missing:
- A note describing that the `sptoken` parameter will be on the query string for form POSTs, instead of in the POST body (which the JSON-only example implies)
- The second form field (`passwordAgain`)
- Validation check that the first and second fields match - I think we explicitly want to always check this locally before sending off to the server?

This is currently how Express works (and others I believe).

### PR DESCRIPTION
**Pull request by nbarbettini**
Fixes #86

I wanted to bring this section up to parity to what Express is already doing. I don't think this will be a breaking change with existing implementations, but I'm not 100% sure. I think it's important to clarify this, but we don't have to include it in v1.0 if we don't want to.

### CODE REVIEW

**Comment by nbarbettini** [comment]
Looking for any thoughts from @robertjd when he has time

**Comment by edjiang** [comment]
Change the password again parameter

**Comment by nbarbettini** [comment]
> Change the password again parameter

`passwordAgain` is the current name in Express and others. Are we saying we want to change this?

**Comment by nbarbettini** [comment]
Nate will split this into a documentation-only change, and icebox the remainder of the discussion.

**Comment by lhazlewood** [comment]
It is `confirmPassword` in the Java integrations.  I think this better conveys the purpose of the field.

**Comment by nbarbettini** [comment]
This PR is now a documentation update only - no spec changes. Ready to merge :+1:

**Pull request merged**
